### ISSUE TITLE
Hide trend for Medtronic Enlight CGM

### ISSUE THREAD

**Issue by yuzhuk** [kashamalasha/nightscout-widget-electron#23]
Medtronic Enlight sensors do not provide trend readings, so now "-" (hyphen) is always displayed in this case. It would be nice to hide it altogether to keep the readout clean.

I don't know if this also applies to Guardian CGM or not.

**Comment by kashamalasha** [comment]
The trend calculation functionality was added to the application in 
https://github.com/kashamalasha/nightscout-widget-electron/releases/tag/v0.6.0-beta
