### ISSUE TITLE
Default values for mg/dl

### ISSUE THREAD

**Issue by lostboy86** [kashamalasha/nightscout-widget-electron#66]
When option for Mg/Dl value is selectend, 

the default values remains for the mmol setup.

Add Default values for mg/dl if this option choose

**Comment by reloadfast** [comment]
Issue is reproducible on a fresh install, win10.

![Owlet1](https://github.com/kashamalasha/nightscout-widget-electron/assets/7727512/db86a5ca-5ebf-43e5-991d-2c61c38ac35c)
