### ISSUE TITLE
widget preferences window doesn't move

### ISSUE THREAD

**Issue by painbrain81** [kashamalasha/nightscout-widget-electron#68]
like title.
it's impossibile to move.
it's not good if you place widget in bottom right of the screen and the widget preferences windows opens just OUTSIDE the screen :)

**Comment by kashamalasha** [comment]
Please tell me a bit about your current environment to reproduce the behavior.
Thanks.

**Comment by painbrain81** [comment]
![1](https://github.com/kashamalasha/nightscout-widget-electron/assets/24631990/0f149086-01ce-4041-b485-ba8ea72c2170)
i install 0.6.1 beta

**Comment by painbrain81** [comment]
i explane better....
the preference widget window doesn't move BUT if you move "attached" widget... you can move window too.

**Comment by kashamalasha** [comment]
Fixed in [v0.6.3-beta](https://github.com/kashamalasha/nightscout-widget-electron/releases/tag/v0.6.3-beta)
