### ISSUE TITLE
link POEDITOR broken

### ISSUE THREAD

**Issue by painbrain81** [kashamalasha/nightscout-widget-electron#70]
i want to contribute to traslate app in italian but the link is broken

https://poeditor.com/projects/view?id=640131

![1](https://github.com/kashamalasha/nightscout-widget-electron/assets/24631990/d7ccafc5-2e0c-44b4-a1e8-ffd993bd9dee)

**Comment by kashamalasha** [comment]
Send me your e-mail, I'll invite you to contribute to the POEditor project.
The link is broken probably because of the free plan, I need to clarify it with the POE support team.

**Comment by kashamalasha** [comment]
Fixed in [v0.6.3-beta](https://github.com/kashamalasha/nightscout-widget-electron/releases/tag/v0.6.3-beta)
