### ISSUE TITLE
graphical issue

### ISSUE THREAD

**Issue by painbrain81** [kashamalasha/nightscout-widget-electron#72]
top right and left
![1](https://github.com/kashamalasha/nightscout-widget-electron/assets/24631990/ec1cac9f-7ed2-46bf-8abe-63d3cb0012d2)

**Comment by kashamalasha** [comment]
Could you describe your environment?
OS, Version, and which package did you use to install the application?

**Comment by painbrain81** [comment]
![1](https://github.com/kashamalasha/nightscout-widget-electron/assets/24631990/0f149086-01ce-4041-b485-ba8ea72c2170)
i install 0.6.1 beta

**Comment by kashamalasha** [comment]
Thanks. I'll try to reproduce it.

**Comment by Alamo04** [comment]
Confirmed with Windows 11 and latest Exe Version.
But its only a realy minor visual bug.

**Comment by kashamalasha** [comment]
I can't reproduce it on my MS virtual machines, but I saw it many times on some users' machines. I deem that is an Electron bug. Could we register a bug in the Electron project? Mark this comment with an 👍 sign, and I'll send you an instruction on how to prepare for this. Thanks.

**Comment by painbrain81** [comment]
it looks like solved with 0.8 version... i wait few day for close issue 👍

**Comment by painbrain81** [comment]
new versione solved (i tried with two pc).
