### ISSUE TITLE
Glucose color

### ISSUE THREAD

**Issue by orineo1** [kashamalasha/nightscout-widget-electron#75]
Hello!
First and foremost, I want to express my appreciation for the excellent app—thank you!

I've noticed an issue where the color of the glucose is consistently red when I use the mg/dL option for reasons unknown.

Similarly, when opting for the mmol/L option, the color appears to be consistently grey.

thanks!

**Comment by painbrain81** [comment]
app doesn't change glucose level when you change from mol to mg/dl and viceversa. you have to change accordingly with your settings to view correct colors

**Comment by orineo1** [comment]
You're right!
Thank you :)
