### ISSUE TITLE
POEditor link is broken

### ISSUE THREAD

**Issue by reloadfast** [kashamalasha/nightscout-widget-electron#84]
The POEditor link in the Readme is broken, 404, https://poeditor.com/projects/view?id=640131.
I would like to help with the Spanish translation.

**Comment by kashamalasha** [comment]
Yeah! I'll replace it with the request to contribute. You can say your e-mail, I'll add you as a contributor for the project.

**Comment by reloadfast** [comment]
Hit me: reload.fast@gmail.com
